import { createAction } from '@reduxjs/toolkit';

export const AUTHENTICATION_USER_ACTION_TYPES = {
  FETCH_AUTHENTICATION_USER_PROFILE:
    '[AUTHENTICATION_USER_STATE] - FETCH_AUTHENTICATION_USER_PROFILE',
  FETCH_AUTHENTICATION_USER_PROFILE_SUCCESS:
    '[AUTHENTICATION_USER_STATE] - FETCH_AUTHENTICATION_USER_PROFILE_SUCCESS',
  FETCH_AUTHENTICATION_USER_PROFILE_FAILURE:
    '[AUTHENTICATION_USER_STATE] - FETCH_AUTHENTICATION_USER_PROFILE_FAILURE'
};

export const AUTHENTICATION_USER_ACTIONS = {
  fetchAuthenticationUserProfile: createAction(AUTHENTICATION_USER_ACTION_TYPES.FETCH_AUTHENTICATION_USER_PROFILE),
  fetchAuthenticationUserProfileSuccess: createAction(
    AUTHENTICATION_USER_ACTION_TYPES.FETCH_AUTHENTICATION_USER_PROFILE_SUCCESS,
    responseData => ({
      payload: responseData
    })
  ),
  fetchAuthenticationUserProfileFailure: createAction(
    AUTHENTICATION_USER_ACTION_TYPES.FETCH_AUTHENTICATION_USER_PROFILE_FAILURE,
    errorDescription => ({
      payload: errorDescription
    })
  )
};
